cp_name = "linux kernel"
blob_file = "./exemplar_only/blobs/CVE-2022-32250_solve.bin"
harness_id = "id_11"
sanitizer_id = "id_3"
bug_introduce_commit = "6a9b77f89970dc08c0ca651dedf97b9fd88a8ad7"
src_dir = "./src/linux_kernel"
