cp_name = "linux kernel"
blob_file = "./exemplar_only/blobs/CROMU-00001_solve.bin"
harness_id = "id_6"
sanitizer_id = "id_1"
bug_introduce_commit = "80327b878ff1607d0eae00d35b4a1177da6475dd"
src_dir = "./src/linux_kernel"
