cp_name = "linux kernel"
blob_file = "./exemplar_only/blobs/CVE-2022-0185_solve.bin"
harness_id = "id_10"
sanitizer_id = "id_1"
bug_introduce_commit = "0e17852cf5fbcc67bcddbf8f7ab773e67cbb4a7d"
src_dir = "./src/linux_kernel"
