cp_name = "linux kernel"
blob_file = "./exemplar_only/blobs/repro"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "6e5be40d32fb1907285277c02e74493ed43d77fe"
src_dir = "./src/linux_kernel"
