cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "c763b9440189b541316054ba4f623e728b5aae77~1"
src_dir = "./src/harfbuzz"
