cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "34ba6c726925efceaa2cc995d7d4b0409907f331~1"
src_dir = "./src/htslib"
