cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "8aa97af0cbf5ce37a17937f8001f270cf2f6d805~4"
src_dir = "./src/c-blosc2"
