cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "81c2fcd59368a9c57da77416066e731a7183a57d~3"
src_dir = "./src/c-blosc2"
