cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "790fb01e1c33c5c83e7f3e051fe6c6d5c3396ade~3"
src_dir = "./src/libexif"
