cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "1c667a762c4272ec970a2dd6f945836c52f35720~0"
src_dir = "./src/lcms"
