cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "b916bd061121852f7025f3610ae0074f8d597f7f~0"
src_dir = "./src/open62541"
