cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "8fa85769e7d61bbb3b6e731ff5e935b0b63a1469~0"
src_dir = "./src/lcms"
