cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "30e50906596aa69a484c1044abb07eaa0ffda2dd~0"
src_dir = "./src/libexif"
