cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "115e42ee34bd34899a8ea29b1118efdf543588b1~0"
src_dir = "./src/openexr"
