cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "73d84b602bd35f74be6d01e712c0617fd99b6e47~0"
src_dir = "./src/hunspell"
