cp_name = "ARVO"
blob_file = "./exemplar_only/cpv_1/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "ddec95be6412f2fe41eec33b299f4b2d5babbd0c~0"
src_dir = "./src/hunspell"
