cp_name = "jenkins"
blob_file = "./exemplar_only/cpv_exemplar/blobs/sample_solve.bin"
harness_id = "id_1"
sanitizer_id = "id_1"
bug_introduce_commit = "d4860a8ac8b8c1d4642357840adb4347f7ade43a"
src_dir = "./src/plugins/pipeline-util-plugin"