cp_name = "linux kernel"
blob_file = "./exemplar_only/blobs/CVE-2023-2513_solve.bin"
harness_id = "id_15"
sanitizer_id = "id_3"
bug_introduce_commit = "4c853087c7cb3820188e3a33c371f77fb1eece3e"
src_dir = "./src/linux_kernel"
