cp_name = "linux kernel"
blob_file = "./exemplar_only/blobs/CVE-2021-38208_solve.bin"
harness_id = "id_13"
sanitizer_id = "id_4"
bug_introduce_commit = "573d1bba8b19321b69ebaadabc06f947245a4248"
src_dir = "./src/linux_kernel"
