cp_name = "linux kernel"
blob_file = "./exemplar_only/blobs/CVE-2022-0995_solve.bin"
harness_id = "id_4"
sanitizer_id = "id_1"
bug_introduce_commit = "71055d99a49075d7c6994b8497b61c44eb980512"
src_dir = "./src/linux_kernel"
